[project]
name = "cron"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "John Gorriceta", email = "johngorriceta1@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "boto3>=1.40.0",
    "lxml>=6.1.2",
    "pillow>=11.0.0",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "requests>=2.32.0",
    "SQLAlchemy>=2.0",
]

[project.scripts]
cron = "cron:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
